const AUTHENTICATED = 'AUTHENTICATED'
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED' 

const HAS_ANIMAL = 'HAS_ANIMAL';
const NO_HAS_ANIMAL = 'NO_HAS_ANIMAL';

export {AUTHENTICATED, NOT_AUTHENTICATED, NO_HAS_ANIMAL, HAS_ANIMAL}
